version: "3.6"

services:
  database:
    image: "postgres:15-alpine"
    container_name: database
    #restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=easytaskdb
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - database:/var/lib/postgresql/data

  # frontend:
  #   image: "frontend:latest"
  #   container_name: frontend
  #   build: ./frontend
  #   #restart: on-failure
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"

  # backend:
  #   image: "backend:latest"
  #   container_name: backend
  #   build: ./backend
  #   #restart: on-failure
  #   depends_on:
  #     - backend-mysql
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://backend-mysql:3306/easytaskdb?useUnicode=true&characterEncoding=utf8&useSSL=false&&allowPublicKeyRetrieval=true
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=rootroot
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #   ports:
  #     - "8080:8080"

volumes:
  database:
    driver: local
