spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/easytaskdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'